name: Generate Test Artifacts on GitHub-Hosted Runner
on: [push]
jobs:
  test_on_ubuntu:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('Tests'),test
  test_on_mac:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: macos-10.15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('Tests'),test